import { PDS4_INFO_MODEL } from "./pds4-info-model";

export type Investigation = {
  [PDS4_INFO_MODEL.LID]:string;
  [PDS4_INFO_MODEL.REF_LID_TARGET]:string[];
  [PDS4_INFO_MODEL.REF_LID_INSTRUMENT_HOST]:string[];
  [PDS4_INFO_MODEL.VID]:string;
  [PDS4_INFO_MODEL.ALIAS.ALTERNATE_TITLE]:string;
  [PDS4_INFO_MODEL.INVESTIGATION.DESCRIPTION]:string;
  [PDS4_INFO_MODEL.INVESTIGATION.START_DATE]:string;
  [PDS4_INFO_MODEL.INVESTIGATION.STOP_DATE]:string;
  [PDS4_INFO_MODEL.IDENTIFICATION_AREA.TITLE]:string;
  [PDS4_INFO_MODEL.INVESTIGATION.TYPE]:string;
  [PDS4_INFO_MODEL.IDENTIFICATION_AREA.VERSION_ID]:string;
}