version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "develop"
    # Always increase the version requirement
    # to match the new version.
    versioning-strategy: increase

  - package-ecosystem: "github-actions" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    target-branch: "develop"

  - package-ecosystem: "docker" # See documentation for possible values
    directory: "/docker/" # Location of package manifests
    schedule:
      interval: "weekly"
    target-branch: "develop"

  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "/terraform/" # Location of package manifests
    schedule:
      interval: "weekly"
    target-branch: "develop"

